version: '3.8'

services:
  db:
    image: postgres:16.5
    environment:
      POSTGRES_DB: social_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  web:
    build: .
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

  cache:
    image: redis:7.2.4
    restart: always
    ports:
      - 6380:6379
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  postgres_data_dev:
